version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    ignore:
      # our lighthouse fork depends on this for proper keygen functionality
      # we can remove this once we implement keygen in house
      - dependency-name: "alloy-primitives"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
