comment:
  layout: "reach"
  behavior: default
  require_changes: true
coverage:
  status:
    project:
      default:
        informational: true
        branches:
          - main
    patch:
      default:
        informational: true
        target: 80%
