name: Setup Deposit CLI
description: Download the EthStaker deposit CLI binary for the target platform
inputs:
  version:
    description: 'Version of the deposit CLI to download'
    required: false
    default: 'v1.2.2'

runs:
  using: composite
  steps:
    - name: Prepare deposit sidecar binary
      shell: bash
      run: |
        set -euo pipefail
        python3 <<'PY'
        import json
        import os
        import pathlib
        import time
        import urllib.request
        import platform
        import sys

        VERSION = "${{ inputs.version }}"
        API_URL = f"https://api.github.com/repos/ethstaker/ethstaker-deposit-cli/releases/tags/{VERSION}"

        # Determine the platform
        system = platform.system().lower()
        machine = platform.machine().lower()

        if system == "linux":
            if machine in ["x86_64", "amd64"]:
                platform_suffix = "linux-amd64"
                target_triple = "x86_64-unknown-linux-gnu"
            else:
                raise SystemExit(f"Unsupported Linux architecture: {machine}")
        elif system == "darwin":
            if machine in ["x86_64", "amd64"]:
                platform_suffix = "darwin-amd64"
                target_triple = "x86_64-apple-darwin"
            elif machine in ["arm64", "aarch64"]:
                platform_suffix = "darwin-arm64"
                target_triple = "aarch64-apple-darwin"
            else:
                raise SystemExit(f"Unsupported macOS architecture: {machine}")
        elif system == "windows":
            if machine in ["x86_64", "amd64"]:
                platform_suffix = "windows-amd64"
                target_triple = "x86_64-pc-windows-msvc"
            else:
                raise SystemExit(f"Unsupported Windows architecture: {machine}")
        else:
            raise SystemExit(f"Unsupported operating system: {system}")

        print(f"Detected platform: {system}/{machine} -> {platform_suffix}")
        print(f"Target triple: {target_triple}")

        # Fetch release information
        with urllib.request.urlopen(API_URL) as response:
            release = json.load(response)

        # Find the appropriate asset
        asset = next(
            (item for item in release["assets"] if platform_suffix in item["name"] and item["name"].endswith(".tar.gz")),
            None,
        )
        if asset is None:
            raise SystemExit(f"Could not locate {platform_suffix} asset for ethstaker deposit CLI {VERSION}")

        print(f"Found asset: {asset['name']}")
        download_url = asset["browser_download_url"]

        # Download with retries
        archive_path = pathlib.Path("/tmp/deposit-cli.tar.gz")
        for attempt in range(5):
            try:
                print(f"Downloading from {download_url} (attempt {attempt + 1}/5)")
                urllib.request.urlretrieve(download_url, archive_path)
                break
            except Exception as exc:
                if attempt == 4:
                    raise
                time.sleep(2)

        # Extract the binary
        import tarfile
        with tarfile.open(archive_path) as tar:
            member = next(m for m in tar.getmembers() if m.name.endswith("/deposit"))
            extracted = tar.extractfile(member)
            data = extracted.read()

        # Write to target location
        target_dir = pathlib.Path("packages/app/src-tauri/bin")
        target_dir.mkdir(parents=True, exist_ok=True)

        binary_name = "deposit.exe" if system == "windows" else "deposit"
        target_path = target_dir / f"{binary_name}-{target_triple}"

        with open(target_path, "wb") as fh:
            fh.write(data)
        os.chmod(target_path, 0o755)

        print(f"Successfully installed deposit CLI to {target_path}")
        PY