name: CI - JavaScript

on:
  push:
    paths:
      - package.json
      - bun.lock
      - kittynode-docs/**
      - kittynode-com/**

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Format and lint
        run: bun -F kittynode-docs -F kittynode-com format-lint

      - name: Svelte check
        run: bun -F kittynode-com check
