name: CI - JavaScript

on:
  push:
    paths:
      - docs/**
      - packages/app/*
      - packages/app/src/**

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Format and lint
        run: bun -F docs -F app -F website format-lint

      - name: Svelte check
        run: bun -F app -F website check
