name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
  merge_group: # Trigger in merge queue to pass the required status check

jobs:
  merge-gatekeeper:
    if: github.event_name == 'pull_request' # Skip in merge queue
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
